'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';

type Exercise={id:string;name:string;muscle_groups:string[];equipment_needed:string[];difficulty:string;category:string;instructions:string[]};
type Profile={experience_level:string;fitness_level:string;primary_goal:string;training_background:string;cardio_level:string;mobility_level:string;limitations:string[]};
type Pick=Exercise&{score:number;why:string;sets:number;reps:string;rest:number};

const defaults:Profile={experience_level:'Intermediate',fitness_level:'Active',primary_goal:'Fat Loss + Muscle Gain',training_background:'General Fitness',cardio_level:'Good',mobility_level:'Good',limitations:['None']};
const experiences=['Beginner','Intermediate','Advanced','Competitive Athlete'];
const fitness=['Deconditioned','Average','Active','Athletic','Highly Athletic'];
const backgrounds=['General Fitness','Bodybuilding','Powerlifting','Running','MMA','BJJ','Wrestling','Boxing','Football','Basketball','Other'];
const levels=['Poor','Average','Good','Excellent'];
const limitations=['Shoulder Issues','Knee Issues','Back Issues','Ankle Issues','None'];
const goals=['Fat Loss','Fat Loss + Muscle Gain','Build Muscle','Strength','Athletic Performance','MMA/BJJ Performance','General Fitness'];
const splits=['push','pull','legs','upper','lower','full','mma'];
const homeEquipment=['bodyweight','pull-up bar','doorway pull-up bar','resistance band','long resistance band','mini band','dumbbell','adjustable dumbbells','fixed dumbbells','kettlebell','weight vest','dip bars','rings','suspension trainer','jump rope','medicine ball','foam roller','bench','plyo box'];
const garageEquipment=['barbell','plates','squat rack','power rack','flat bench','adjustable bench','landmine attachment'];
const gymEquipment=['machine','machines','cable','cable machines','smith machine','leg press','assisted pull-up machine','functional trainer'];
const allEquipment=[...homeEquipment,...garageEquipment,...gymEquipment,'box'];
const defaultGear=['bodyweight','dumbbell','pull-up bar','resistance band','bench'];

export default function CoachPage(){
 const supabase=useMemo(()=>createClient(),[]);
 const [userId,setUserId]=useState<string|null>(null),[email,setEmail]=useState<string|null>(null),[msg,setMsg]=useState('Loading...');
 const [profile,setProfile]=useState<Profile>(defaults),[exercises,setExercises]=useState<Exercise[]>([]),[goal,setGoal]=useState('Fat Loss + Muscle Gain'),[split,setSplit]=useState('full'),[minutes,setMinutes]=useState(45),[gear,setGear]=useState<string[]>(defaultGear),[workout,setWorkout]=useState<Pick[]>([]);
 const tier=getTier(profile);
 useEffect(()=>{async function load(){const {data:s}=await supabase.auth.getSession();const u=s.session?.user;if(!u){setMsg('Sign in on the main page first.');return}setUserId(u.id);setEmail(u.email??null);const [{data:p},{data:e,error}]=await Promise.all([supabase.from('profiles').select('experience_level,fitness_level,primary_goal,training_background,cardio_level,mobility_level,limitations,equipment_profile').eq('id',u.id).maybeSingle(),supabase.from('exercises').select('*').order('name')]);if(p){const row=p as Partial<Profile>&{equipment_profile?:string[]};setProfile({...defaults,...row,limitations:Array.isArray(row.limitations)&&row.limitations.length?row.limitations:['None']});if(Array.isArray(row.equipment_profile)&&row.equipment_profile.length)setGear(row.equipment_profile);if(row.primary_goal)setGoal(row.primary_goal)}if(error)setMsg(error.message);else{setExercises((e as Exercise[]??[]).map(x=>({...x,muscle_groups:x.muscle_groups??[],equipment_needed:x.equipment_needed??['bodyweight'],instructions:x.instructions??[]})));setMsg('Ready. Set profile, gear, and generate.')}}load()},[supabase]);
 async function saveProfile(){if(!userId)return setMsg('Sign in first.');const {error}=await supabase.from('profiles').update({...profile,primary_goal:goal,equipment_profile:gear,profile_completed:true}).eq('id',userId);setMsg(error?error.message:`Saved. ${tier.label} profile and ${gear.length} equipment choices are active.`)}
 function update<K extends keyof Profile>(k:K,v:Profile[K]){setProfile(o=>({...o,[k]:v}))}
 function toggle(v:string){setGear(g=>g.includes(v)?g.filter(x=>x!==v):[...g,v])}
 function toggleLimit(v:string){if(v==='None')return update('limitations',['None']);const next=profile.limitations.includes(v)?profile.limitations.filter(x=>x!==v):[...profile.limitations.filter(x=>x!=='None'),v];update('limitations',next.length?next:['None'])}
 function useSavedEquipment(){setGear(gear.length?gear:defaultGear);setMsg('Equipment profile loaded into this workout setup.')}
 function generate(){const count=minutes<=30?4:minutes<=45?5:6;const pool=exercises.filter(e=>matchesGear(e,gear)&&matchesSplit(e,split));const source=(pool.length>=3?pool:exercises.filter(e=>matchesGear(e,gear))).map(e=>scoreExercise(e,profile,goal,split,gear)).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);const picks:Pick[]=[];const wanted=plan(split,goal,profile);for(const w of wanted){const found=source.find(x=>!picks.some(p=>p.id===x.id)&&(x.category.toLowerCase().includes(w)||pattern(x)===w||w==='any'));if(found)picks.push(makePick(found,goal,profile))}for(const x of source){if(picks.length>=count)break;if(!picks.some(p=>p.id===x.id))picks.push(makePick(x,goal,profile))}setWorkout(picks.slice(0,count));setMsg(picks.length?`Generated for ${tier.label}. ${goal} logic and equipment filters applied.`:'No matching exercises. Add bodyweight, dumbbells, pull-up bar, or bands.')}
 return <main className="min-h-screen bg-[#080a0f] px-4 py-6 text-white"><section className="mx-auto flex max-w-md flex-col gap-5 pb-24"><header className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-orange-500/20 to-white/5 p-5"><p className="text-sm font-semibold text-orange-300">ForgeFit Coach / Profile</p><h1 className="mt-1 text-3xl font-black">Tailored Training</h1><p className="mt-2 text-sm text-zinc-300">This is now the main Coach/Profile tab for ability level, equipment, fat-loss logic, and tailored workouts.</p><p className="mt-2 text-xs text-zinc-400">{email??'Not signed in'}</p><Link href="/" className="mt-4 inline-block rounded-2xl bg-white px-4 py-3 text-sm font-black text-black">Back to main app</Link></header>
 <Panel title="Athlete profile" note={tier.label}><Select label="Experience" value={profile.experience_level} options={experiences} onChange={v=>update('experience_level',v)}/><Select label="Fitness level" value={profile.fitness_level} options={fitness} onChange={v=>update('fitness_level',v)}/><Select label="Main goal" value={goal} options={goals} onChange={v=>{setGoal(v);update('primary_goal',v)}}/><Select label="Background" value={profile.training_background} options={backgrounds} onChange={v=>update('training_background',v)}/><Select label="Cardio" value={profile.cardio_level} options={levels} onChange={v=>update('cardio_level',v)}/><Select label="Mobility" value={profile.mobility_level} options={levels} onChange={v=>update('mobility_level',v)}/><Chooser title="Limitations" options={limitations} selected={profile.limitations} onToggle={toggleLimit}/></Panel>
 <Panel title="Equipment profile" note={`${gear.length} selected`}><Chooser title="At home" options={homeEquipment} selected={gear} onToggle={toggle}/><Chooser title="Garage gym" options={garageEquipment} selected={gear} onToggle={toggle}/><Chooser title="Commercial gym" options={gymEquipment} selected={gear} onToggle={toggle}/><button onClick={saveProfile} className="mt-4 w-full rounded-2xl bg-orange-500 px-4 py-3 font-black text-black">Save profile + equipment</button><p className="mt-3 text-xs text-zinc-400">Saved equipment is used by the tailored generator. Bodyweight-only will avoid machines, cables, barbells, and dumbbells.</p></Panel>
 <Panel title="Workout setup" note={`${exercises.length} exercises loaded`}><Select label="Goal" value={goal} options={goals} onChange={setGoal}/><Select label="Split" value={split} options={splits} onChange={setSplit}/><label className="mt-3 block rounded-2xl bg-black/25 p-3"><span className="text-xs font-bold uppercase text-zinc-400">Minutes</span><input value={minutes} onChange={e=>setMinutes(Number(e.target.value))} type="number" className="mt-2 w-full bg-transparent text-2xl font-black outline-none"/></label><button onClick={useSavedEquipment} className="mt-4 w-full rounded-2xl bg-white/10 px-4 py-3 text-sm font-black">Use saved equipment profile</button><button onClick={generate} className="mt-4 w-full rounded-2xl bg-orange-500 px-4 py-4 font-black text-black">Generate personalized workout</button><p className="mt-3 text-sm text-orange-200">{msg}</p></Panel>
 {!!workout.length&&<Panel title="Generated workout" note="coach logic"><div className="flex flex-col gap-3">{workout.map((e,i)=><article key={e.id} className="rounded-2xl border border-white/10 bg-black/25 p-4"><p className="text-xs text-orange-300">#{i+1} · {e.category} · {e.difficulty} · score {Math.round(e.score)}</p><h3 className="text-lg font-black">{e.name}</h3><p className="text-sm text-zinc-300">{e.sets} sets · {e.reps} · rest {e.rest}s</p><p className="mt-1 text-xs text-zinc-400">Why: {e.why}</p><p className="mt-1 text-xs text-zinc-500">Needs: {e.equipment_needed.join(', ')||'bodyweight'}</p></article>)}</div></Panel>}
 </section></main>}

function getTier(p:Profile){let tier=3;if(p.experience_level==='Beginner'||p.fitness_level==='Deconditioned')tier=1;else if(p.fitness_level==='Average')tier=2;else if(p.fitness_level==='Athletic'||p.experience_level==='Advanced')tier=4;if(p.fitness_level==='Highly Athletic'||p.experience_level==='Competitive Athlete')tier=5;return{tier,label:['','Tier 1 Beginner','Tier 2 General Fitness','Tier 3 Active','Tier 4 Athletic','Tier 5 Competitive'][tier]}}
function eq(x:string){const v=x.toLowerCase();if(v.includes('pull-up')||v.includes('dip'))return'bar';if(v.includes('dumbbell'))return'dumbbell';if(v.includes('band'))return'resistance band';if(v.includes('cable')||v.includes('trainer'))return'cable';if(v.includes('machine')||v==='leg press')return'machine';if(v.includes('bench'))return'bench';if(v.includes('box'))return'box';return v}
function matchesGear(e:Exercise,gear:string[]){const req=(e.equipment_needed??[]).map(eq),g=gear.map(eq);return!req.length||req.includes('bodyweight')||req.some(r=>g.includes(r))}
function mus(e:Exercise){return(e.muscle_groups??[]).join(' ').toLowerCase()}
function pattern(e:Exercise){const n=e.name.toLowerCase(),m=mus(e);if(/jump|bound|slam|pogo|throw/.test(n))return'power';if(/row|pull|chin/.test(n))return'pull';if(/press|push|dip|fly/.test(n))return'push';if(/squat|step|lunge|leg press/.test(n))return'squat';if(/rdl|deadlift|curl|thrust|hamstring/.test(n))return'hinge';if(/carry|crawl|sprawl|burpee|rope/.test(n)||e.category==='conditioning')return'conditioning';if(m.includes('core')||e.category==='core')return'core';return e.category.toLowerCase()}
function matchesSplit(e:Exercise,s:string){const m=mus(e),p=pattern(e);if(s==='full')return true;if(s==='push')return p==='push'||m.includes('chest')||m.includes('shoulders')||m.includes('triceps');if(s==='pull')return p==='pull'||m.includes('back')||m.includes('biceps');if(s==='legs'||s==='lower')return ['squat','hinge','power'].includes(p)||/legs|quad|hamstring|glute|calf/.test(m);if(s==='upper')return /chest|back|shoulder|arm|biceps|triceps/.test(m);if(s==='mma')return ['power','conditioning','core','squat','hinge','pull','push'].includes(p);return true}
function scoreExercise(e:Exercise,p:Profile,goal:string,split:string,gear:string[]){const tier=getTier(p).tier,d=e.difficulty?.toLowerCase(),pat=pattern(e),cat=e.category.toLowerCase();let score=matchesSplit(e,split)?60:15;let why='matches split';if(tier<=2){if(d==='beginner')score+=25;if(d==='advanced')score-=45;if(['power','conditioning'].includes(pat))score-=10;why='scaled easier for ability'}if(tier>=4){if(['intermediate','advanced'].includes(d))score+=18;if(['power','conditioning','core'].includes(pat))score+=14;why='scaled up for athletic ability'}if(goal.includes('Fat Loss')){score+=cat.includes('strength')||cat.includes('hypertrophy')?8:0;if(tier<=2&&pat==='conditioning')score+=3;if(tier>=3&&['conditioning','power','core'].includes(pat))score+=18;why+=' + fat-loss muscle-preserving logic'}if(['MMA','BJJ','Wrestling','Boxing'].includes(p.training_background)&&['power','conditioning','core'].includes(pat)){score+=16;why+=' + sport carryover'}if(gear.map(eq).length===1&&gear.map(eq)[0]==='bodyweight'&&!matchesGear(e,['bodyweight']))score-=100;if(p.limitations.some(l=>l.includes('Knee'))&&['squat','power'].includes(pat))score-=25;if(p.limitations.some(l=>l.includes('Shoulder'))&&['push','pull','power'].includes(pat))score-=20;if(p.limitations.some(l=>l.includes('Back'))&&pat==='hinge')score-=20;if((e.equipment_needed??[]).some(r=>gear.map(eq).includes(eq(r))))score+=10;return{...e,score,why}}
function plan(split:string,goal:string,p:Profile){if(goal.includes('Fat Loss'))return getTier(p).tier<=2?['strength','push','pull','core','conditioning','any']:['conditioning','strength','power','core','push','pull','any'];if(split==='push')return['push','push','core','conditioning','any'];if(split==='pull')return['pull','pull','core','conditioning','any'];if(split==='legs')return['squat','hinge','power','core','conditioning','any'];if(split==='mma')return['power','conditioning','core','pull','push','any'];return['push','pull','squat','hinge','core','conditioning','any']}
function makePick(e:ReturnType<typeof scoreExercise>,goal:string,p:Profile):Pick{const tier=getTier(p).tier;return{...e,sets:tier<=2?2:goal.includes('Build')?4:3,reps:e.category==='power'?'3-5':e.category==='conditioning'?(tier<=2?'20-30 sec':'30-60 sec'):goal.includes('Strength')?'4-6':goal.includes('Fat')?'10-15':'8-12',rest:e.category==='conditioning'?(tier<=2?60:40):goal.includes('Strength')?120:60}}
function Panel({title,note,children}:{title:string;note:string;children:React.ReactNode}){return <section className="rounded-[2rem] border border-white/10 bg-white/5 p-5"><p className="text-sm font-semibold text-orange-300">{note}</p><h2 className="mt-1 text-xl font-black">{title}</h2><div className="mt-4">{children}</div></section>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="mt-3 block rounded-2xl bg-black/25 p-3"><span className="text-xs font-bold uppercase text-zinc-400">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/40 px-3 py-3 text-white">{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Chooser({title,options,selected,onToggle}:{title:string;options:string[];selected:string[];onToggle:(v:string)=>void}){return <div className="mt-4"><p className="text-xs font-bold uppercase tracking-[0.18em] text-zinc-400">{title}</p><div className="mt-2 flex flex-wrap gap-2">{options.map(o=><button key={o} onClick={()=>onToggle(o)} className={`rounded-full px-3 py-2 text-xs font-bold ${selected.includes(o)?'bg-orange-500 text-black':'bg-white/10 text-zinc-200'}`}>{o}</button>)}</div></div>}
